name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.3
  - seaborn=0.11.1
  - pandas=2.0.1
  - pip=23.1.2
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.15.2