name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - mlflow=2.3.2
  - numpy=1.24.3
  - ipython=8.12.2
  - notebook=6.5.4
  - jupyterlab=3.6.3
  - seaborn=0.11.1
  - pandas=2.0.1
  - pip=23.1.2
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.15.2