name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.1
  - pip=23.1.2
  - mlflow=2.3.2
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.15.2
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
