name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.1
  - pip=23.1.2
  - mlflow=2.3.2
  - scikit-learn=0.24.1
  - matplotlib=3.7.1
  - pillow=8.1.2
  - pip:
      - wandb==0.15.2
